tokenizer:
  model_name: /xinbei_data/replug/baseline/experiments/t5l-rewrite_try0303/
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: llm
  args:
    pid: 0

datapool:
  id: TQA
  args:
    prompt_prefix: "rewrite a search query for Wikipedia: "


env:
  n_envs: 5
  args:
    max_prompt_length: 512
    max_episode_length: 50
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

alg:
  id: ppo
  args: 
    n_steps: 512
    batch_size: 16
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 4
    ent_coef: 0.0
  kl_div:
    coeff: 0.001
    target_kl: 0.2
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: /xinbei_data/replug/baseline/experiments/t5l-rewrite_try0303/bl_model
      apply_model_parallel: True
      prompt_truncation_side: "right"
      generation_kwargs:
        min_length: 1
        max_length: 50
        num_return_sequences: 1
        num_beams: 4          
    
train_evaluation:
  eval_batch_size: 16
  n_iters: 50
  eval_every: 1
  save_every: 1
  metrics:
    - id: llm
      args: 
        pid: 0
    # - id: rouge
    # - id: bleu
    #   args: {}
    # - id: bert_score
    #   args:
    #     language: en
    # - id: bleurt
    #   args:
    #     config_name: bleurt-large-512
    # - id: diversity
    #   args: {}
    # - id: summaCZS
    #   args:
    #     granularity: sentence
    #     use_ent: True
    #     use_con: False
    # - id: summaCConv
    #   args:
    #     granularity: sentence
  generation_kwargs: 
    min_length: 1
    max_length: 50
    num_return_sequences: 1
    num_beams: 4

